Add a DAG based pipeline option
latticesurgery-com/liblsqecc pull request #69
Opened 2023-03-12 22:50 UTC by gwwatkin

The new pipeline does the following:
 1. Takes the LSInstruction Steram
 2. Reads it all and makes on big DAG (as shown in #65 )
 3. Layers the dag onto slices

This pipeline is still experimental but already improves the BoundaryRotation and SGate cases which can now successfully be parallelized. E.g. The following before was not possible, because every SGate would result in a new slice (the same applies to rotations, which would each trigger 2 new slices)
![Screenshot_20230312_154809](https://user-images.githubusercontent.com/36427091/224578640-5f055c96-e770-4b83-9f13-1fcc4dbc5fa3.png)
![Screenshot_20230312_154957](https://user-images.githubusercontent.com/36427091/224578658-b15ca2e0-fb8d-4aa8-adb8-bd1b6fecf258.png)

2023-03-14 18:13 UTC, tylerrleblond commented
Thanks for implementing this much-needed feature to the compiler. Some immediate observations that I hope will be helpful in further improving it:

- Applying -P dag to test case print_dag/input_lli.case.sh and comparing the sliced (.json) output with the output using --printdag processedlli, I notice:
	- With high levels of parallelism, the visualization becomes hard to read (many adjacent teal tiles make it impossible to unambiguously determine what is happening without referencing side-by-side with --printdag processedlli or --printlli sliced)
	- MultiBodyMeasure 2:Z,3:Z doesn't seem to occur in any slice
- Doing the same with print_dag/processed_lli.case.sh:
	- The RotateSingleCellPatch 4 and MultiBodyMeasure 0:Z,4:Z don't seem to occur in any slice
- Doing the same with cases/edpc_layout_tests/2.case.sh:
	- It skips waiting for magic states and goes right to the S gate layer
	- For some reason, it is not using an ancilla to generate a Y state in order to perform an S gate but is doing something on each logical qubit individually
- Doing the same with cases/edpc_layout_tests/3.case.sh:
	- Looks great

2023-03-14 19:54 UTC, tylerrleblond requested changes
Thanks for implementing this much-needed feature to the compiler. Some immediate observations that I hope will be helpful in further improving it:

- Applying -P dag to test case print_dag/input_lli.case.sh and comparing the sliced (.json) output with the output using --printdag processedlli, I notice:
	- With high levels of parallelism, the visualization becomes hard to read (many adjacent teal tiles make it impossible to unambiguously determine what is happening without referencing side-by-side with --printdag processedlli or --printlli sliced)
	- MultiBodyMeasure 2:Z,3:Z doesn't seem to occur in any slice
- Doing the same with print_dag/processed_lli.case.sh:
	- The RotateSingleCellPatch 4 and MultiBodyMeasure 0:Z,4:Z don't seem to occur in any slice
- Doing the same with cases/edpc_layout_tests/2.case.sh:
	- It skips waiting for magic states and goes right to the S gate layer
	- For some reason, it is not using an ancilla to generate a Y state in order to perform an S gate but is doing something on each logical qubit individually
- Doing the same with cases/edpc_layout_tests/3.case.sh:
	- Looks great
- Doing the same with cases/edpc_layout_tests/1.case.sh
	- The obstruction still does not cause the code to crash (I think this was expected to be resolved with better parallelism)

Before merging, I think that the issue with missing instructions needs to be resolved.

2023-03-17 16:26 UTC, gwwatkin commented
Discussed offline. There is indeed one outstanding bug, which is the missing instructions.

This is a major issue with this pipeline and is blocking for a release. Tracking it here
 - 73

However, this changes adds a lot of useful infrastructure which is possible to start working on. So, for the purpose of keeping things moving, I propose merging it

2023-03-17 17:00 UTC, tylerrleblond approved these changes

2023-03-18 22:04 UTC, merged